title: BSides Oslo - May 23rd, 2019
description: BSides is an inclusive information security event that is focused on learning and sharing.
event: BSides Oslo
date: May 23rd, 2019
email_info: info@bsidesoslo.no
email_cfp: cfp@bsidesoslo.no
twitter_username: oslobsides


sass:
  sass_dir: "src/styles"

exclude: ['src']

defaults:
- scope:
    path: ""
  values:
    layout: "default"
