title: BSides Oslo - May 23rd, 2019
description: BSides is an inclusive information security event that is focused on learning and sharing.
event: BSides Oslo
location: MESH
date: May 23rd, 2019
email_info: info@bsidesoslo.no
email_sponsorship: sponsors@bsidesoslo.no
email_cfp: cfp@bsidesoslo.no
cfp_form: https://goo.gl/forms/dWVz94nK7Ohkn3eK2
twitter_username: oslobsides

sponsors:
  gold:
  - name: Nagarro
    logo: Nagarro.png
    website: https://www.nagarro.com/en
  - name: Bouvet
    logo: Bouvet.png
    website: https://www.bouvet.no
  - name: Basefarm
    logo: Basefarm.png
    website: https://www.basefarm.com/no/
  standard:
  community:


sass:
  sass_dir: "src/styles"

exclude: ['src', 'node_modules', 'gulpfile.js','.sass-cache']

defaults:
- scope:
    path: ""
  values:
    layout: "default"
