title: BSides Oslo - May 23rd, 2019
description: BSides is an inclusive information security event that is focused on learning and sharing.
event: BSides Oslo
location: MESH
date: May 23rd, 2019
email_info: info@bsidesoslo.no
email_sponsorship: sponsors@bsidesoslo.no
email_cfp: cfp@bsidesoslo.no
cfp_form: https://goo.gl/forms/dWVz94nK7Ohkn3eK2
twitter_username: oslobsides


sass:
  sass_dir: "src/styles"

exclude: ['src']

defaults:
- scope:
    path: ""
  values:
    layout: "default"
